### ISSUE TITLE
Help for YT-DL-Webinterface

### ISSUE THREAD

**Issue by mikagrand** [Watn3y/YT-DL-Webinterface#3]
Hello,
I want to know if you can help me with your script, i want you to no restrict to youtube source video only but to all ytdlp supported source.
Also i don't want to store the videos files on my server.

Thanks.

**Comment by Watn3y** [comment]
Hi,

I had no idea this issue existed. Sorry, I didn't reply. Feel free to open a new one if you're still interested.
